# Generated by Django 3.0.6 on 2020-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20200623_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerdetails',
            name='end_quiz',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
